### ISSUE TITLE
note though that in contrast to your instructions I do not have h5py version 2.1

### ISSUE THREAD

**Issue by smith6jt-cop** [AlbertPun/TRAILMAP#12]
note though that in contrast to your instructions I do not have h5py version 2.1
```
pip3 install h5py==2.1
```

as this version is no longer available on PyPI for installation with pip nor is it available with conda-forge. I tried to build version 2.1 from sources but haven't had luck so far. I also doubt that 2.1 would have produced incompatible hdf5 files.

Edited to add:

I have tested h5py version 2.6 and version 2.10 on Linux. HDFView was an older install on Windows.

_Originally posted by @VolkerH in https://github.com/AlbertPun/TRAILMAP/issues/3#issuecomment-584464864_

**Comment by smith6jt-cop** [comment]
Which version of h5py should be used?

**Comment by citypalmtree** [comment]
@smith6jt-cop Which version of h5py ended up working for you?

**Comment by VolkerH** [comment]
@citypalmtree  

If you look at the whole Thread in  issue #3 you will see that the exact version of h5py is probably not critical.
The errors I initially encountered where due to an incomplete download of the weights h5 file.
By setting up `git lfs` correctly I managed to download a complete weights file that could be openend with newer versions of `h5py`. This was ages ago though and I can't tell you exactly which version number worked.

**Comment by citypalmtree** [comment]
@VolkerH 
Thank you for clarifying that!
It was indeed the weights file not completely being downloaded.
And h5py==3.1 works!
Thank you.
